version: '3.8'

services:
  web:
    image: hsleet/portfolio-web
    command: ["sh", "-c", "python manage.py collectstatic --noinput && gunicorn portfolio.wsgi:application --bind 0.0.0.0:8000"]
    volumes:
      - .:/code
      - static_volume:/vol/static
    expose:
      - 8000
    env_file:
      - .env

  nginx:
    image: hsleet/portfolio-nginx
    volumes:
      - /etc/nginx/ssl:/etc/nginx/ssl
      - static_volume:/vol/static
    ports:
      - "80:80"
      - "443:443"

volumes:
  static_volume: