version: '3.8'

services:
  web:
    build: .
    command: ["gunicorn", "portfolio.wsgi:application", "--bind", "0.0.0.0:8000"]
    volumes:
      - .:/code
      - static_volume:/vol/static
    expose:
      - 8000

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - static_volume:/vol/static
    ports:
      - "80:80"

volumes:
  static_volume:
  