# Generated by Django 4.2.7 on 2023-11-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='small_bio',
            field=models.TextField(max_length=500),
        ),
    ]
