# Generated by Django 4.2.7 on 2023-11-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0002_alter_user_small_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='José Eduardo Méndez Espinal', max_length=200),
            preserve_default=False,
        ),
    ]
