# Generated by Django 4.2.7 on 2023-11-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0003_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skill_images/'),
        ),
    ]
