# Generated by Django 4.2.7 on 2023-11-25 01:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0004_skill_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
