# Generated by Django 4.2.7 on 2023-11-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0005_alter_skill_skill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_title',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
