# Generated by Django 4.2.7 on 2023-11-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0006_project_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/skill_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_images/'),
        ),
    ]
