# Generated by Django 4.2.7 on 2023-11-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0007_alter_skill_image_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.FileField(upload_to='project_images/'),
        ),
    ]
