# Generated by Django 4.2.7 on 2023-11-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0008_alter_projectimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.FileField(upload_to='static/project_images/'),
        ),
    ]
