# Generated by Django 4.2.7 on 2023-11-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0010_alter_project_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hobbies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.TextField(blank=True),
        ),
    ]
