# Generated by Django 4.2.7 on 2023-11-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0011_user_hobbies_user_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='static/resumes/'),
        ),
    ]
