# Generated by Django 4.2.7 on 2023-11-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0012_user_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobexperience',
            name='company',
            field=models.CharField(default='Tevolv', max_length=200),
            preserve_default=False,
        ),
    ]
