# Generated by Django 4.2.7 on 2023-12-12 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0013_jobexperience_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='graduation_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
